markdown: kramdown

gifs:
  - animals
  - boom
  - clap
  - crap
  - dance
  - done
  - excited
  - fuck-you
  - happy
  - hello
  - high-five
  - impressed
  - laughing
  - nope
  - omg
  - sad
  - scared
  - thank-you
  - thats-true
  - think
  - thumbs-up
  - work
  - yep
